import { connectMongo, closeMongo, getDb } from "./db/mongo";
import type { MedicationDoc } from "./domain/medication";

const now = new Date();

const medications: Omit<MedicationDoc, "_id">[] = [
  // --- Dolor ---
  {
    name: "Coriver (Paracetamol) Tab 500mg x20",
    brand: "Maver",
    category: "dolor",
    activeIngredient: "Paracetamol",
    dose: "500mg",
    packageSize: 20,
    priceCents: 112,
    imageUrl: "",
    requiresPrescription: false,
    stock: 200,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Dolver (Ibuprofeno) Tab 400mg x10",
    brand: "Maver",
    category: "dolor",
    activeIngredient: "Ibuprofeno",
    dose: "400mg",
    packageSize: 10,
    priceCents: 129,
    imageUrl: "",
    requiresPrescription: false,
    stock: 150,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Dolprofen (Ibuprofeno) Tab 400mg x10",
    brand: "Collins",
    category: "dolor",
    activeIngredient: "Ibuprofeno",
    dose: "400mg",
    packageSize: 10,
    priceCents: 176,
    imageUrl: "",
    requiresPrescription: false,
    stock: 120,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Afleno (Ibuprofeno) Tab 400mg x10",
    brand: "Bruluagsa",
    category: "dolor",
    activeIngredient: "Ibuprofeno",
    dose: "400mg",
    packageSize: 10,
    priceCents: 134,
    imageUrl: "",
    requiresPrescription: false,
    stock: 100,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Dualgos (Paracetamol/Ibuprofeno) Tab 325/200mg x20",
    brand: "Liferpal",
    category: "dolor",
    activeIngredient: "Paracetamol, Ibuprofeno",
    dose: "325mg / 200mg",
    packageSize: 20,
    priceCents: 257,
    imageUrl: "",
    requiresPrescription: false,
    stock: 80,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Ácido Acetilsalicílico Tab 500mg x20",
    brand: "Alpharma",
    category: "dolor",
    activeIngredient: "Ácido Acetilsalicílico",
    dose: "500mg",
    packageSize: 20,
    priceCents: 86,
    imageUrl: "",
    requiresPrescription: false,
    stock: 180,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Dalivium Tramax (Dexketoprofeno/Tramadol) Tab 25mg x10",
    brand: "Quimpharma",
    category: "dolor",
    activeIngredient: "Dexketoprofeno, Tramadol",
    dose: "25mg / 75mg",
    packageSize: 10,
    priceCents: 302,
    imageUrl: "",
    requiresPrescription: false,
    stock: 60,
    active: true,
    createdAt: now,
    updatedAt: now,
  },

  // --- Gripe ---
  {
    name: "Desenfriol-ito Plus (Paracetamol/Fenilefrina/Clorfenamina) Tab x24",
    brand: "Bayer",
    category: "gripe",
    activeIngredient: "Paracetamol, Fenilefrina, Clorfenamina",
    dose: "500mg / 5mg / 2mg",
    packageSize: 24,
    priceCents: 380,
    imageUrl: "",
    requiresPrescription: false,
    stock: 90,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Panadol Multisíntomas Tab x30",
    brand: "GSK",
    category: "gripe",
    activeIngredient: "Paracetamol, Dextrometorfano, Clorfenamina, Fenilefrina",
    dose: "500mg / 15mg / 2mg / 5mg",
    packageSize: 30,
    priceCents: 389,
    imageUrl: "",
    requiresPrescription: false,
    stock: 100,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Loratadina/Fenilefrina/Paracetamol Tab 12",
    brand: "Similares",
    category: "gripe",
    activeIngredient: "Loratadina, Fenilefrina, Paracetamol",
    dose: "2.5mg / 5mg / 500mg",
    packageSize: 12,
    priceCents: 270,
    imageUrl: "",
    requiresPrescription: false,
    stock: 75,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Coriver (Paracetamol) Tab 750mg x10",
    brand: "Maver",
    category: "gripe",
    activeIngredient: "Paracetamol",
    dose: "750mg",
    packageSize: 10,
    priceCents: 112,
    imageUrl: "",
    requiresPrescription: false,
    stock: 130,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Antitusivo (Dextrometorfano) Tab 15mg x10",
    brand: "Alpharma",
    category: "gripe",
    activeIngredient: "Dextrometorfano",
    dose: "15mg",
    packageSize: 10,
    priceCents: 150,
    imageUrl: "",
    requiresPrescription: false,
    stock: 80,
    active: true,
    createdAt: now,
    updatedAt: now,
  },

  // --- Alergias ---
  {
    name: "Loratadina Tab 10mg x10",
    brand: "AMSA",
    category: "alergias",
    activeIngredient: "Loratadina",
    dose: "10mg",
    packageSize: 10,
    priceCents: 110,
    imageUrl: "",
    requiresPrescription: false,
    stock: 200,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Loratadina Tab 10mg x20",
    brand: "Ultra",
    category: "alergias",
    activeIngredient: "Loratadina",
    dose: "10mg",
    packageSize: 20,
    priceCents: 180,
    imageUrl: "",
    requiresPrescription: false,
    stock: 150,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Cetirizina Tab 10mg x10",
    brand: "Alpharma",
    category: "alergias",
    activeIngredient: "Cetirizina",
    dose: "10mg",
    packageSize: 10,
    priceCents: 120,
    imageUrl: "",
    requiresPrescription: false,
    stock: 140,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Cetirizina Tab 10mg x20",
    brand: "Ultra",
    category: "alergias",
    activeIngredient: "Cetirizina",
    dose: "10mg",
    packageSize: 20,
    priceCents: 200,
    imageUrl: "",
    requiresPrescription: false,
    stock: 100,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Clorfeniramina Tab 4mg x10",
    brand: "Alpharma",
    category: "alergias",
    activeIngredient: "Clorfeniramina",
    dose: "4mg",
    packageSize: 10,
    priceCents: 85,
    imageUrl: "",
    requiresPrescription: false,
    stock: 120,
    active: true,
    createdAt: now,
    updatedAt: now,
  },

  // --- Digestivo ---
  {
    name: "Omeprazol Cap 20mg x14",
    brand: "Alpharma",
    category: "digestivo",
    activeIngredient: "Omeprazol",
    dose: "20mg",
    packageSize: 14,
    priceCents: 132,
    imageUrl: "",
    requiresPrescription: false,
    stock: 100,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Simeticona Tab 80mg x10",
    brand: "Alpharma",
    category: "digestivo",
    activeIngredient: "Simeticona",
    dose: "80mg",
    packageSize: 10,
    priceCents: 95,
    imageUrl: "",
    requiresPrescription: false,
    stock: 90,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Carbonato de Calcio Tab 500mg x30",
    brand: "Alpharma",
    category: "digestivo",
    activeIngredient: "Carbonato de Calcio",
    dose: "500mg",
    packageSize: 30,
    priceCents: 120,
    imageUrl: "",
    requiresPrescription: false,
    stock: 80,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Loperamida Cap 2mg x12",
    brand: "Alpharma",
    category: "digestivo",
    activeIngredient: "Loperamida",
    dose: "2mg",
    packageSize: 12,
    priceCents: 110,
    imageUrl: "",
    requiresPrescription: false,
    stock: 110,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Kalequim (Paracetamol/Tramadol) Tab 325/37.5mg x20",
    brand: "Quimpharma",
    category: "dolor",
    activeIngredient: "Paracetamol, Tramadol",
    dose: "325mg / 37.5mg",
    packageSize: 20,
    priceCents: 320,
    imageUrl: "",
    requiresPrescription: false,
    stock: 65,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
];

async function seed() {
  console.log("Conectando a MongoDB...");
  await connectMongo();
  const db = getDb();
  const col = db.collection<MedicationDoc>("medications");

  console.log("Limpiando colección medications...");
  await col.deleteMany({});

  console.log(`Insertando ${medications.length} medicamentos...`);
  await col.insertMany(medications as MedicationDoc[]);

  console.log("Creando índices...");
  await col.createIndex({ category: 1 });
  await col.createIndex({ name: "text" });
  await db.collection("orders").createIndex({ userId: 1 });
  await db.collection("orders").createIndex({ stripePaymentIntentId: 1 }, { sparse: true });
  await db.collection("payments").createIndex({ stripeSessionId: 1 }, { unique: true });

  console.log("Seed completado.");
  await closeMongo();
}

seed().catch((err) => {
  console.error("Error en seed:", err);
  process.exit(1);
});